### ISSUE TITLE
CSS Routing

### ISSUE THREAD

**Issue by thecodeduchess** [DavidAlip/DevProjects#1]
https://github.com/DavidAlip/DevProjects/blob/760cd909cec872d660a632c003d62f2c8bd8297a/Dasmotos_Arts_and_Crafts/index.html#L6

You have to change this line to start from resources. I don't have your computer, so this routing will only make the styles available to you.

<img width="1179" alt="screen shot 2017-11-21 at 11 38 46 am" src="https://user-images.githubusercontent.com/8722966/33088038-11333d6e-ceb2-11e7-8533-04b95956d095.png">

**Comment by DavidAlip** [comment]
Yes I realized that after clicking submit. Thanks!
